# Generated by Django 5.2.4 on 2025-08-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_add_book", "Can add book"),
                    ("can_change_book", "Can change book"),
                    ("can_delete_book", "Can delete book"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="librarian",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="library",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
